version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  deploy-web:
    working_directory: ~/suspendont/web
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/suspendont
      - node/with-cache:
          cache-version: v2
          dir: ~/suspendont/web
          steps:
            - run: yarn install
      - run: yarn build
      - run: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only hosting

  deploy-functions:
    working_directory: ~/suspendont/functions
    executor:
      name: node/default
    steps:
      - checkout:
          path: ~/suspendont
      - node/install-node:
          version: 10.20.1
      - node/with-cache:
          cache-version: v4
          dir: ~/suspendont/functions
          steps:
            - run: yarn install
      - run: echo "$KEYS" | base64 --decode > keys.json
      - run: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --only functions

workflows:
  deploy-all:
    jobs:
      - deploy-web:
          context: Firebase
      - deploy-functions:
          context: Firebase